"""
Django settings for project project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY", "insecure-dev-key")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DJANGO_DEBUG", "1") == "1"

# Allow all by default for local dev; if DJANGO_ALLOWED_HOSTS is set, make sure
# common dev hosts are included to support Docker compose networking & Vite proxy.
_allowed = [h for h in os.getenv("DJANGO_ALLOWED_HOSTS", "").split(",") if h]
ALLOWED_HOSTS = _allowed or ["*"]
if "*" not in ALLOWED_HOSTS:
    # Add typical hosts seen in local/dev and container-to-container requests
    for h in ("backend", "localhost", "127.0.0.1"):
        if h not in ALLOWED_HOSTS:
            ALLOWED_HOSTS.append(h)

# Railway/production: Allow the Railway-provided domain
if os.getenv("RAILWAY_PUBLIC_DOMAIN"):
    ALLOWED_HOSTS.append(os.getenv("RAILWAY_PUBLIC_DOMAIN"))

# CSRF trusted origins for Railway
CSRF_TRUSTED_ORIGINS = []
if os.getenv("RAILWAY_PUBLIC_DOMAIN"):
    CSRF_TRUSTED_ORIGINS.append(f"https://{os.getenv('RAILWAY_PUBLIC_DOMAIN')}")


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "drf_spectacular",
    "django_filters",
    "corsheaders",
    "phonenumber_field",
    "solo",
    "school",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",  # Serve static files in production
    "corsheaders.middleware.CorsMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    # CSRF middleware can be disabled for API-only dev via DISABLE_CSRF flag below
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "project.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "project.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Railway provides DATABASE_URL; use dj-database-url to parse it
import dj_database_url

DATABASE_URL = os.getenv("DATABASE_URL")
if DATABASE_URL:
    DATABASES = {
        "default": dj_database_url.config(
            default=DATABASE_URL,
            conn_max_age=600,
            conn_health_checks=True,
        )
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            # Provide sane defaults so the container works out-of-the-box if .env is missing
            "NAME": os.getenv("POSTGRES_DB", "drivingschool"),
            "USER": os.getenv("POSTGRES_USER", "drivingschool"),
            "PASSWORD": os.getenv("POSTGRES_PASSWORD", "drivingschoolpwd"),
            "HOST": os.getenv("DB_HOST", "localhost"),
            "PORT": os.getenv("DB_PORT", "5432"),
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_DIRS = []

# WhiteNoise for serving static files in production
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

# Media files (user-uploaded content)
MEDIA_URL = "media/"
MEDIA_ROOT = BASE_DIR / "media"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# CORS (allow all in dev; tighten later)
CORS_ALLOW_ALL_ORIGINS = True

# Business-local timezone for availability calculations (admin & backend logic)
# Keep TIME_ZONE=UTC for storage; use BUSINESS_TZ for human scheduling rules.
BUSINESS_TZ = os.getenv("BUSINESS_TZ", "Europe/Chisinau")

REST_FRAMEWORK = {
    # Use a pagination class compatible with react-admin (?page & ?page_size)
    "DEFAULT_PAGINATION_CLASS": "school.pagination.StandardResultsSetPagination",
    "DEFAULT_FILTER_BACKENDS": [
        "django_filters.rest_framework.DjangoFilterBackend",
        "rest_framework.filters.OrderingFilter",
    ],
    # Open permissions for initial development to avoid 403/permission denied.
    # IMPORTANT: tighten before production (e.g., IsAuthenticated / token auth).
    "DEFAULT_PERMISSION_CLASSES": ["rest_framework.permissions.AllowAny"],
    # Enable JWT auth for clients that send Authorization: Bearer <token>.
    # Endpoints remain accessible due to AllowAny permissions by default;
    # we can tighten per-view later by setting IsAuthenticated.
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ],
    "EXCEPTION_HANDLER": "school.exceptions.exception_handler",
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
}

# Structured logging (console) for clearer debugging during development.
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "simple": {"format": "[%(asctime)s] %(levelname)s %(name)s: %(message)s"},
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "simple",
        },
    },
    "loggers": {
        "school": {  # our app
            "handlers": ["console"],
            "level": "DEBUG" if DEBUG else "INFO",
            "propagate": False,
        },
        "django.request": {  # request errors
            "handlers": ["console"],
            "level": "ERROR",
            "propagate": False,
        },
    },
}

# drf-spectacular OpenAPI schema settings
SPECTACULAR_SETTINGS = {
    "TITLE": "Driving School API",
    "DESCRIPTION": "API schema for the Driving School backend (enums, students, enrollments, etc.).",
    "VERSION": "0.1.0",
    "SERVE_INCLUDE_SCHEMA": False,
}

# Extra permissive CORS / CSRF dev settings to prevent forbidden errors while iterating
CORS_ALLOW_CREDENTIALS = True
# If frontend served from another origin (e.g., http://localhost:3000)
_frontend = os.getenv("FRONTEND_ORIGIN", "http://localhost:3000")
CSRF_TRUSTED_ORIGINS = [h for h in [_frontend, "http://localhost", "http://127.0.0.1"] if h]

# Dev flag to disable CSRF protection (ONLY for local development!)
DISABLE_CSRF = os.getenv("DISABLE_CSRF", "1") == "1"

if DISABLE_CSRF:
    # Remove CsrfViewMiddleware dynamically so unsafe methods don't raise 403
    MIDDLEWARE = [m for m in MIDDLEWARE if m != "django.middleware.csrf.CsrfViewMiddleware"]

# SimpleJWT settings (sane dev defaults; override via env in production)
from datetime import timedelta  # noqa: E402

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=int(os.getenv("JWT_ACCESS_MINUTES", "30"))),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=int(os.getenv("JWT_REFRESH_DAYS", "7"))),
    "ROTATE_REFRESH_TOKENS": False,
    "BLACKLIST_AFTER_ROTATION": False,
    "SIGNING_KEY": os.getenv("JWT_SIGNING_KEY", SECRET_KEY),
    "AUTH_HEADER_TYPES": ("Bearer",),
}

# Email settings
EMAIL_BACKEND = os.getenv("EMAIL_BACKEND", "django.core.mail.backends.console.EmailBackend")
DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL", "noreply@drivingschool.com")

# File upload settings
FILE_UPLOAD_MAX_MEMORY_SIZE = 5242880  # 5MB in bytes
DATA_UPLOAD_MAX_MEMORY_SIZE = 5242880  # 5MB in bytes

# Phone number field settings
PHONENUMBER_DEFAULT_REGION = "MD"  # Moldova as default region
PHONENUMBER_DEFAULT_FORMAT = "INTERNATIONAL"  # E.164 format
