# Generated by Django 4.2.22 on 2025-09-17 06:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("school", "0002_add_custom_user_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="consent_recorded",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="student",
            name="consent_timestamp",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="student",
            name="notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="student",
            name="preferred_language",
            field=models.CharField(
                choices=[("en", "English"), ("ro", "Romanian"), ("ru", "Russian")],
                default="en",
                max_length=5,
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="student",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("active", "Active"),
                    ("inactive", "Inactive"),
                    ("graduated", "Graduated"),
                    ("dropped", "Dropped"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddConstraint(
            model_name="student",
            constraint=models.UniqueConstraint(
                fields=("email",), name="unique_student_email"
            ),
        ),
    ]
