# Generated by Django 4.2.24 on 2025-09-15 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_instructor_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='last_service',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='maintenance_due',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='next_service',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='service_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
