# Generated by Django 5.2.6 on 2025-09-23 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0004_student_password_alter_course_category_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="enrollment",
            unique_together={("student", "course", "type")},
        ),
    ]
