# Generated by Django 4.2.24 on 2025-09-16 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_vehicle_maintenance'),
        ('school', '0004_merge_migrations'),
    ]

    operations = [
    ]
