# Generated by Django 5.2.6 on 2025-09-23 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_alter_enrollment_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together=set(),
        ),
    ]
