# Generated by Django 4.2.24 on 2025-09-16 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_merge_0002_vehicle_maintenance_0004_merge_migrations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='last_service',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='maintenance_due',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='maintenance_status',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='next_service',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='service_notes',
        ),
        migrations.AddField(
            model_name='student',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='student',
            name='consent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='consent_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='language',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='progress_practical',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='progress_theory',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
