# Generated by Django 5.2.6 on 2025-09-24 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_alter_enrollment_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='duration_minutes',
            field=models.IntegerField(default=60),
        ),
        migrations.CreateModel(
            name='InstructorAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('MONDAY', 'Monday'), ('TUESDAY', 'Tuesday'), ('WEDNESDAY', 'Wednesday'), ('THURSDAY', 'Thursday'), ('FRIDAY', 'Friday'), ('SATURDAY', 'Saturday'), ('SUNDAY', 'Sunday')], max_length=10)),
                ('hours', models.JSONField(default=list, help_text="List of available start times in HH:MM format, e.g. ['08:00', '09:30']")),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='school.instructor')),
            ],
            options={
                'unique_together': {('instructor', 'day')},
            },
        ),
    ]
