# Generated by Django 5.2.3 on 2025-11-11 07:41

import django.core.validators
import school.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0009_resource_remove_lesson_vehicle_lesson_resource_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='email',
            field=models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator()]),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='first_name',
            field=models.CharField(max_length=50, validators=[school.validators.django_validate_name]),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='last_name',
            field=models.CharField(max_length=50, validators=[school.validators.django_validate_name]),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='phone_number',
            field=models.CharField(max_length=20, unique=True, validators=[school.validators.django_validate_phone]),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator()]),
        ),
        migrations.AlterField(
            model_name='student',
            name='first_name',
            field=models.CharField(max_length=50, validators=[school.validators.django_validate_name]),
        ),
        migrations.AlterField(
            model_name='student',
            name='last_name',
            field=models.CharField(max_length=50, validators=[school.validators.django_validate_name]),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone_number',
            field=models.CharField(max_length=20, unique=True, validators=[school.validators.django_validate_phone]),
        ),
    ]
