# Generated by Django 5.2.7 on 2025-10-31 00:35

from django.db import migrations


def migrate_vehicles_to_resources(apps, schema_editor):
    """Migrate existing Vehicle data to Resource model."""
    Vehicle = apps.get_model('school', 'Vehicle')
    Resource = apps.get_model('school', 'Resource')

    for vehicle in Vehicle.objects.all():
        Resource.objects.create(
            name=f"{vehicle.make} {vehicle.model}",
            max_capacity=2,  # Vehicles hold 2 people (driver + instructor)
            category=vehicle.category,
            is_available=vehicle.is_available,
            license_plate=vehicle.license_plate,
            make=vehicle.make,
            model=vehicle.model,
            year=vehicle.year,
        )


def update_lessons_to_use_resources(apps, schema_editor):
    """Update existing Lessons to reference Resources instead of Vehicles."""
    Lesson = apps.get_model('school', 'Lesson')
    Resource = apps.get_model('school', 'Resource')

    for lesson in Lesson.objects.filter(vehicle__isnull=False):
        # Find the corresponding resource for this vehicle
        try:
            resource = Resource.objects.get(
                license_plate=lesson.vehicle.license_plate
            )
            lesson.resource = resource
            lesson.save(update_fields=['resource'])
        except Resource.DoesNotExist:
            # If no matching resource found, set to None
            lesson.resource = None
            lesson.save(update_fields=['resource'])


def create_default_classrooms(apps, schema_editor):
    """Create some default classroom resources."""
    Resource = apps.get_model('school', 'Resource')

    # Create default classrooms
    classrooms = [
        {"name": "Classroom A", "max_capacity": 30, "category": "B"},
        {"name": "Classroom B", "max_capacity": 25, "category": "B"},
        {"name": "Classroom C", "max_capacity": 20, "category": "A"},
    ]

    for classroom in classrooms:
        Resource.objects.create(
            name=classroom["name"],
            max_capacity=classroom["max_capacity"],
            category=classroom["category"],
            is_available=True,
            # Vehicle-specific fields remain null for classrooms
        )


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0009_resource_remove_lesson_vehicle_lesson_resource_and_more'),
    ]

    operations = [
        migrations.RunPython(
            migrate_vehicles_to_resources,
            reverse_code=migrations.RunPython.noop  # No reverse migration needed
        ),
        migrations.RunPython(
            update_lessons_to_use_resources,
            reverse_code=migrations.RunPython.noop
        ),
        migrations.RunPython(
            create_default_classrooms,
            reverse_code=migrations.RunPython.noop
        ),
    ]
