# Generated by Django 5.2.3 on 2025-11-11 08:08

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0010_alter_instructor_email_alter_instructor_first_name_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="resource",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("license_plate"),
                condition=models.Q(("license_plate__isnull", False), ("max_capacity", 2)),
                name="unique_vehicle_license_plate_ci",
            ),
        ),
    ]
