# Generated by Django 5.2.3 on 2025-11-11 08:26

import django.db.models.functions.text
import school.validators
from django.db import migrations, models


def dedupe_vehicle_plates(apps, schema_editor):
    Resource = apps.get_model('school', 'Resource')
    from django.db.models.functions import Lower
    from django.db.models import Q

    seen = {}
    qs = Resource.objects.filter(Q(max_capacity__lte=2) & Q(license_plate__isnull=False))
    for r in qs:
        plate = (r.license_plate or '').strip().lower()
        if not plate:
            continue
        if plate in seen:
            # Clear plate on duplicates to allow unique constraint to be created
            r.license_plate = None
            r.save(update_fields=['license_plate'])
        else:
            seen[plate] = r.id


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0011_resource_unique_vehicle_license_plate_ci"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="resource",
            name="unique_vehicle_license_plate_ci",
        ),
        migrations.RunPython(dedupe_vehicle_plates, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name="instructor",
            name="license_categories",
            field=models.CharField(
                help_text="Comma separated categories: e.g. 'B,BE,C' ",
                max_length=200,
                validators=[school.validators.django_validate_license_categories],
            ),
        ),
        migrations.AddConstraint(
            model_name="resource",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("license_plate"),
                condition=models.Q(("license_plate__isnull", False), ("max_capacity__lte", 2)),
                name="unique_vehicle_license_plate_ci",
            ),
        ),
    ]
