# Generated by Django 5.2.8 on 2025-11-13 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0012_remove_resource_unique_vehicle_license_plate_ci_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduledclass',
            name='course',
        ),
        migrations.RemoveField(
            model_name='scheduledclass',
            name='instructor',
        ),
        migrations.RemoveField(
            model_name='scheduledclass',
            name='resource',
        ),
        migrations.RemoveField(
            model_name='scheduledclass',
            name='students',
        ),
        migrations.CreateModel(
            name='ScheduledClassPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g., 'Theory Mondays/Wednesdays'", max_length=100)),
                ('recurrence_days', models.JSONField(default=list, help_text="List of days: e.g. ['MONDAY', 'WEDNESDAY']")),
                ('times', models.JSONField(default=list, help_text="List of start times: e.g. ['10:00', '11:00']")),
                ('start_date', models.DateField(help_text='Start date for the recurrence')),
                ('num_lessons', models.IntegerField(help_text='Total number of lessons to generate')),
                ('duration_minutes', models.IntegerField(default=60)),
                ('max_students', models.IntegerField()),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('COMPLETED', 'Completed'), ('CANCELED', 'Canceled')], default='SCHEDULED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_class_patterns', to='school.course')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_class_patterns', to='school.instructor')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_class_patterns', to='school.resource')),
                ('students', models.ManyToManyField(blank=True, related_name='scheduled_class_patterns', to='school.student')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='scheduledclass',
            name='pattern',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_classes', to='school.scheduledclasspattern'),
        ),
    ]
