# Generated by Django 5.2.8 on 2025-11-14 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0013_remove_scheduledclass_course_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Addresses',
            },
        ),
        migrations.CreateModel(
            name='SchoolConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(default='Driving School', max_length=200)),
                ('school_logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('business_hours', models.CharField(default='Mon-Fri: 9AM-6PM', max_length=200)),
                ('email', models.EmailField(default='contact@school.com', max_length=254)),
                ('contact_phone1', models.CharField(default='+37360000000', max_length=20)),
                ('contact_phone2', models.CharField(blank=True, max_length=20, null=True)),
                ('landing_image', models.ImageField(blank=True, null=True, upload_to='landing/')),
                ('landing_text', models.JSONField(default=dict, help_text="Translation dictionary for landing page text, e.g., {'en': 'Welcome', 'ro': 'Bun venit'}")),
                ('social_links', models.JSONField(default=dict, help_text="Social media links, e.g., {'facebook': 'https://...', 'instagram': 'https://...'}")),
                ('rules', models.JSONField(default=dict, help_text="Business rules, e.g., {'min_theory_hours_before_practice': 20}")),
                ('available_categories', models.JSONField(default=list, help_text="Available license categories, e.g., ['A', 'B', 'C']")),
                ('addresses', models.ManyToManyField(blank=True, related_name='school_configs', to='school.address')),
            ],
            options={
                'verbose_name': 'School Configuration',
            },
        ),
    ]
