# Generated by Django 5.2.8 on 2025-11-15 01:00

import school.model_validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0013_remove_scheduledclass_course_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolconfig',
            name='landing_image',
            field=models.ImageField(blank=True, help_text='Landing page hero image (max 5MB, formats: jpg, png, gif, webp)', null=True, upload_to='landing/', validators=[school.model_validators.validate_landing_image]),
        ),
        migrations.AlterField(
            model_name='schoolconfig',
            name='school_logo',
            field=models.ImageField(blank=True, help_text='School logo image (max 5MB, formats: jpg, png, gif, webp)', null=True, upload_to='logos/', validators=[school.model_validators.validate_school_logo]),
        ),
    ]
