# Generated by Django 5.2.8 on 2025-11-17 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0013_remove_scheduledclass_course_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='scheduledclasspattern',
            index=models.Index(fields=['start_date'], name='school_sche_start_d_36fcf8_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduledclasspattern',
            index=models.Index(fields=['status'], name='school_sche_status_7a2dd9_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduledclasspattern',
            index=models.Index(fields=['course'], name='school_sche_course__971d2d_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduledclasspattern',
            index=models.Index(fields=['instructor'], name='school_sche_instruc_84d751_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduledclasspattern',
            index=models.Index(fields=['resource'], name='school_sche_resourc_5d9ec9_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduledclasspattern',
            index=models.Index(fields=['start_date', 'status'], name='school_sche_start_d_929d9f_idx'),
        ),
    ]
