# Generated by Django 5.2.8 on 2025-11-15 00:00

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0014_address_schoolconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolconfig',
            name='contact_phone1',
            field=phonenumber_field.modelfields.PhoneNumberField(default='+37360000000', help_text='Primary contact phone number in international format', max_length=128, region=None),
        ),
        migrations.AlterField(
            model_name='schoolconfig',
            name='contact_phone2',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Secondary contact phone number (optional)', max_length=128, null=True, region=None),
        ),
    ]
