# Generated by Django 5.2.8 on 2025-11-17 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0014_add_pattern_indexes'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='scheduledclass',
            index=models.Index(fields=['pattern'], name='school_sche_pattern_273fd7_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduledclass',
            index=models.Index(fields=['scheduled_time'], name='school_sche_schedul_ea733f_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduledclass',
            index=models.Index(fields=['status'], name='school_sche_status_6e0e2b_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduledclass',
            index=models.Index(fields=['scheduled_time', 'status'], name='school_sche_schedul_1dac0e_idx'),
        ),
    ]
