# Generated by Django 5.2.8 on 2025-11-17 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0015_add_scheduled_class_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledclass',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='scheduled_classes', to='school.student'),
        ),
    ]
