# Generated by Django 5.2.8 on 2025-11-19 01:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0017_remove_pattern_class_fields'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='scheduledclasspattern',
            name='school_sche_status_7a2dd9_idx',
        ),
        migrations.RemoveIndex(
            model_name='scheduledclasspattern',
            name='school_sche_start_d_929d9f_idx',
        ),
        migrations.AddField(
            model_name='scheduledclass',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_classes', to='school.course'),
        ),
        migrations.AddField(
            model_name='scheduledclass',
            name='instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_classes', to='school.instructor'),
        ),
        migrations.AddField(
            model_name='scheduledclass',
            name='resource',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_classes', to='school.resource'),
        ),
        migrations.AlterField(
            model_name='scheduledclasspattern',
            name='default_duration_minutes',
            field=models.IntegerField(default=60, help_text='Default duration for generated classes'),
        ),
        migrations.AlterField(
            model_name='scheduledclasspattern',
            name='default_max_students',
            field=models.IntegerField(default=10, help_text='Default max students for generated classes'),
        ),
        migrations.AddIndex(
            model_name='scheduledclasspattern',
            index=models.Index(fields=['start_date', 'course'], name='school_sche_start_d_18089d_idx'),
        ),
    ]
