# Generated by Django 5.2.8 on 2025-11-20 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0018_remove_scheduledclasspattern_school_sche_status_7a2dd9_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='type',
            field=models.CharField(choices=[('VEHICLE', 'Vehicle'), ('CLASSROOM', 'Classroom')], default='VEHICLE', max_length=20),
        ),
        migrations.AlterField(
            model_name='resource',
            name='category',
            field=models.CharField(blank=True, choices=[('AM', 'Am'), ('A1', 'A1'), ('A2', 'A2'), ('A', 'A'), ('B1', 'B1'), ('B', 'B'), ('C1', 'C1'), ('C', 'C'), ('D1', 'D1'), ('D', 'D'), ('BE', 'Be'), ('C1E', 'C1E'), ('CE', 'Ce'), ('D1E', 'D1E'), ('DE', 'De')], max_length=5, null=True),
        ),
    ]
