# Generated by Django 5.2.8 on 2025-11-24 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0014_address_schoolconfig'),
        ('school', '0019_resource_type_alter_resource_category'),
    ]

    operations = [
    ]
