# Generated by Django 5.2.8 on 2025-11-29 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0021_merge_phone_validation'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
